name: connect to AWS role
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: "eu-west-2"

permissions:
  id-token: write
  contents: read

jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::649683443955:role/tonksdev-github-actions
          role-session-name: GitHub_to_AWS
          aws-region: ${{ env.AWS_REGION }}
      - name: GetCallerIdentity
        run: |
          aws sts get-caller-identity
  
      
  
